
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('directs').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('directs').insert({stateid: 1, plan_name: 'College Counts 529', state: 'Alabama', link:'https://www.collegecounts529.com'}),
        knex('directs').insert({stateid: 2, plan_name: 'T-Row Price College Savings Plan', state: 'Alaska', link:'https://www3.troweprice.com/usis/personal-investing/products-and-services/college-savings-plans/t-rowe-price-college-savings-plan/portfolio-options-and-performance/historical-performance.html'}),
        knex('directs').insert({stateid: 3, plan_name: 'Fidelity Arizona College Savings Plan', state: 'Arizona', link:'https://www.fidelity.com/arizona-529/'}),
        knex('directs').insert({stateid: 4, plan_name: 'GIFT College Investing Plan', state: 'Arkansas', link:'https://www.arkansas529.org/'}),
        knex('directs').insert({stateid: 5, plan_name: 'The ScholarShare College Savings Plan', state: 'California', link:'https://www3.troweprice.com/usis/personal-investing/products-and-services/college-savings-plans/t-rowe-price-college-savings-plan/portfolio-options-and-performance/historical-performance.html'}),
        knex('directs').insert({stateid: 6, plan_name: 'Direct Portfolio College Savings Plan', state: 'Colorado', link:'https://www.collegeinvest.org/our-savings-plans/direct-portfolio'}),
        knex('directs').insert({stateid: 7, plan_name: 'Connecticut Higher Education Trust (CHET)', state: 'Connecticut', link:'https://www.aboutchet.com/'}),
        knex('directs').insert({stateid: 8, plan_name: 'Delaware College Investment Plan', state: 'Delaware', link:'https://www.fidelity.com/delaware-529/?immid=100027&imm_pid=126697125&imm_aid=a299952490&dfid=&buf=99999999'}),
        knex('directs').insert({stateid: 9, plan_name: 'DC 529 College Savings Program (Direct-sold)', state: 'District of Colombia', link:'http://www.dccollegesavings.com/'}),
        knex('directs').insert({stateid: 10, plan_name: 'Florida 529 Savings Plan', state: 'Florida', link:'http://www.myfloridaprepaid.com/what-we-offer/529-savings-plan/'}),
        knex('directs').insert({stateid: 11, plan_name: 'Path2College 529 Plan', state: 'Georgia', link:'https://www.path2college529.com/'}),
        knex('directs').insert({stateid: 12, plan_name: "Hawaii's College Savings Program", state: 'Hawaii', link:'https://www.hi529.com/'}),
        knex('directs').insert({stateid: 13, plan_name: 'Idaho College Savings Program (IDeal)', state: 'Idaho', link:'https://www.idsaves.org/'}),
        knex('directs').insert({stateid: 14, plan_name: 'Bright Start College Savings Program', state: 'Illinois', link:'https://www.Brightstartsavings.com'}),
        knex('directs').insert({stateid: 15, plan_name: 'CollegeChoice 529 Direct Savings Plan', state: 'Indiana', link:'https://www.collegechoicedirect.com/'}),
        knex('directs').insert({stateid: 16, plan_name: 'College Savings Iowa', state: 'Iowa', link:'https://www.collegesavingsiowa.com/'}),
        knex('directs').insert({stateid: 17, plan_name: 'Learning Quest 529 Education Savings Program', state: 'Kansas', link:'https://www.learningquest.com/'}),
        knex('directs').insert({stateid: 18, plan_name: 'Kentucky Education Savings Plan Trust', state: 'Kentucky', link:'https://www.kysaves.com/'}),
        knex('directs').insert({stateid: 19, plan_name: 'START Saving Program', state: 'Louisiana', link:'http://www.startsaving.la.gov/savings/index.jsp'}),
        knex('directs').insert({stateid: 20, plan_name: 'NextGen College Investing Plan', state: 'Maine', link:'http://www.nextgenforme.com/'}),
        knex('directs').insert({stateid: 21, plan_name: 'College Savings Plans of Maryland', state: 'Maryland', link:'https://maryland529.com/college-savings-plans-of-maryland/maryland-college-investment-plan'}),
        knex('directs').insert({stateid: 22, plan_name: 'U.Fund College Investing Plan', state: 'Massachusetts', link:'https://www.fidelity.com/massachusetts-529/'}),
        knex('directs').insert({stateid: 23, plan_name: 'Michigan Education Savings Program', state: 'Michigan', link:'https://www.misaves.com/research/historic.shtml'}),
        knex('directs').insert({stateid: 24, plan_name: "Minnesota College Savings Plan", state: 'Minnesota', link:'https://www.mnsaves.org/'}),
        knex('directs').insert({stateid: 25, plan_name: 'Mississippi Affordable College Savings', state: 'Mississippi', link:'https://www.ms529.com/'}),
        knex('directs').insert({stateid: 26, plan_name: "MOST Missouri's 529 College Savings Plan", state: 'Missouri', link:'https://www.missourimost.org/'}),
        knex('directs').insert({stateid: 27, plan_name: 'Achieve Montana', state: 'Montana', link:'https://www.missourimost.org/'}),
        knex('directs').insert({stateid: 28, plan_name: 'Nebraska Education Savings Trust', state: 'Nebraska', link:'https://www.nest529direct.com/'}),
        knex('directs').insert({stateid: 29, plan_name: 'The Vanguard 529 Savings Plan', state: 'Nevada', link:'https://investor.vanguard.com/529-plan/vanguard-529-plan'}),
        knex('directs').insert({stateid: 30, plan_name: 'UNIQUE College Investing Plan', state: 'New Hampshire', link:'https://www.fidelity.com/new-hampshire-529/'}),
        knex('directs').insert({stateid: 31, plan_name: 'NJBEST 529 College Savings Plan', state: 'New Jersey', link:'https://www.njbest.com/'}),
        knex('directs').insert({stateid: 32, plan_name: "The Education Plan's College Savings Program", state: 'New Mexico', link:'https://www.theeducationplan.com/OFI529/'}),
        knex('directs').insert({stateid: 33, plan_name: "New York's 529 College Savings Program", state: 'New York', link:'https://www.nysaves.org/'}),
        knex('directs').insert({stateid: 34, plan_name: 'National College Savings Program', state: 'North Carolina	', link:'http://nc529.org/'}),
        knex('directs').insert({stateid: 35, plan_name: 'College SAVE', state: 'North Dakota', link:'https://www.collegesave4u.com/'}),
        knex('directs').insert({stateid: 36, plan_name: "Ohio CollegeAdvantage Direct 529 Savings Plan", state: 'Ohio', link:'https://www.collegeadvantage.com/'}),
        knex('directs').insert({stateid: 37, plan_name: 'Oklahoma College Savings Plan', state: 'Oklahoma', link:'https://www.okdream529.com/'}),
        knex('directs').insert({stateid: 38, plan_name: 'Oregon College Savings Plan', state: 'Oregon', link:'https://www.oregoncollegesavings.com/'}),
        knex('directs').insert({stateid: 39, plan_name: 'Pennsylvania 529 Investment Plan', state: 'Pennsylvania', link:'https://www.collegeboundsaver.com/'}),
        knex('directs').insert({stateid: 40, plan_name: 'CollegeBound Saver (Direct-sold)', state: 'Road Island', link:'https://www.collegeboundsaver.com/'}),
        knex('directs').insert({stateid: 41, plan_name: 'Future Scholar 529 College Savings Plan', state: 'South Carolina', link:'https://www.futurescholar.com/'}),
        knex('directs').insert({stateid: 42, plan_name: 'CollegeAccess 529 (Direct-sold)', state: 'South Dakota', link:'https://www.collegeaccess529.com/'}),
        knex('directs').insert({stateid: 43, plan_name: 'TNStars College Savings 529 Program', state: 'Tennessee', link:'http://tnstars.com/'}),
        knex('directs').insert({stateid: 44, plan_name: 'Texas College Savings Plan', state: 'Texas', link:'https://www.texascollegesavings.com/'}),
        knex('directs').insert({stateid: 45, plan_name: 'Utah Educational Savings Plan (UESP)', state: 'Utah', link:'https://uesp.org/'}),
        knex('directs').insert({stateid: 46, plan_name: 'Vermont Higher Education Investment Plan', state: 'Vermont', link:'https://vheip.org/'}),
        knex('directs').insert({stateid: 47, plan_name: 'Virginia529 inVEST', state: 'Virginia', link:'http://www.virginia529.com/invest/'}),
        knex('directs').insert({stateid: 49, plan_name: "SMART529 WV Direct College Savings Plan", state: 'West Virginia', link:'http://www.smart529.com'}),
        knex('directs').insert({stateid: 50, plan_name: "Edvest", state: 'Wisconsion', link:'https://www.edvest.com/'}),
      ]);
    });
};
