
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('states').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('states').insert({name: 'Alabama', state_tax_deduction: '$10,000', load:'3.5', hasAdvisors:true,  advisorAlink:1, advisorBlink: 1, advisorClink: 1}),
        knex('states').insert({name: 'Alaska', state_tax_deduction: 'No state tax', load:'5', hasAdvisors:true,  advisorAlink:2, advisorBlink: 2, advisorClink: 2  }),
        knex('states').insert({name: 'Arizona', state_tax_deduction: '$4,000', load:'5.75',hasAdvisors:true, advisorAlink:3, advisorBlink: 3, advisorClink: 3}),
        knex('states' ).insert({name: 'Arkansas', state_tax_deduction: '$10,000', load: 'none', hasAdvisors: false, shouldDoDirect: true, advisorAlink:4, advisorBlink: 4, advisorClink: 4}),
        knex('states').insert({name: 'California', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Colorado', state_tax_deduction: 'Full state tax', load: '3.5',hasAdvisors:true, advisorAlink:6, advisorBlink: 6, advisorClink: 6 }),
        knex('states').insert({name: 'Connecticut', state_tax_deduction: '$10,000', load:'5.5',hasAdvisors:true, advisorAlink:5, advisorBlink: 5, advisorClink: 5}),
        knex('states').insert({name: 'Delaware', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'District of Colombia', state_tax_deduction: '$8,000', load: '3.75',hasAdvisors:true, advisorAlink:7, advisorBlink: 7, advisorClink: 7 }),
        knex('states').insert({name: 'Florida', state_tax_deduction: 'No state tax', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Georgia', state_tax_deduction: '$4,000', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Hawaii', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Idaho', state_tax_deduction: '$8,000', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Illinois', state_tax_deduction: '$20,000', load: '3.5',hasAdvisors:true, advisorAlink:8, advisorBlink: 8, advisorClink: 8  }),
        knex('states').insert({name: 'Indiana', state_tax_deduction: '$1,000 (tax credit)', load:'5.25',hasAdvisors:true, advisorAlink:9, advisorBlink: 9, advisorClink: 9}),
        knex('states').insert({name: 'Iowa', state_tax_deduction: '$6,376', load: '4.75',hasAdvisors:true, advisorAlink:10, advisorBlink: 10, advisorClink: 10 }),
        knex('states').insert({name: 'Kansas', state_tax_deduction: '$6,000', load:'5.75',hasAdvisors:true, advisorAlink:11, advisorBlink: 11, advisorClink: 11 }),
        knex('states').insert({name: 'Kentucky', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Louisiana', state_tax_deduction: '$4,800', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Maine', state_tax_deduction: '$250', load:'5.25',hasAdvisors:true }),
        knex('states').insert({name: 'Maryland', state_tax_deduction: '$5,000', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Massachusetts', state_tax_deduction: '$2,000',load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Michigan', state_tax_deduction: '$10,000', load: '4.5',hasAdvisors:true, advisorAlink:13, advisorBlink: 13, advisorClink: 13 }),
        knex('states').insert({name: 'Minnesota', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Mississippi', state_tax_deduction: '$20,000', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Missouri', state_tax_deduction: '$16,000', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Montana', state_tax_deduction: '$6,000', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Nebraska', state_tax_deduction: '$10,000', load: '4.75',hasAdvisors:true,  advisorAlink:15, advisorBlink: 15, advisorClink: 15 }),
        knex('states').insert({name: 'Nevada', state_tax_deduction: 'No state tax', load:'5.75',hasAdvisors:true, advisorAlink:14, advisorBlink: 14, advisorClink: 14 }),
        knex('states').insert({name: 'New Hampshire', state_tax_deduction: 'No deductions', load: '3.75',hasAdvisors:true, advisorAlink:17, advisorBlink: 17, advisorClink: 17 }),
        knex('states').insert({name: 'New Jersey', state_tax_deduction: 'No deductions', load:'5.75',hasAdvisors:true, advisorAlink:16, advisorBlink: 16, advisorClink: 16 }),
        knex('states').insert({name: 'New Mexico', state_tax_deduction: 'Full state tax', load: '4.75',hasAdvisors:true, advisorAlink:18, advisorBlink: 18, advisorClink: 18 }),
        knex('states').insert({name: 'New York', state_tax_deduction: '$10,000' , load:'5.25',hasAdvisors:true, advisorAlink:19, advisorBlink: 19, advisorClink: 19 }),
        knex('states').insert({name: 'North Carolina', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'North Dakota', state_tax_deduction: '$10,000', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Ohio', state_tax_deduction: '$2,000', load:'5.25',hasAdvisors:true, advisorAlink:20, advisorBlink: 20, advisorClink: 20 }),
        knex('states').insert({name: 'Oklahoma', state_tax_deduction: '$20,000', load: '4.25',hasAdvisors:true, advisorAlink:21, advisorBlink: 21, advisorClink: 21 }),
        knex('states').insert({name: 'Oregon', state_tax_deduction: '$4,620', load:'5.75',hasAdvisors:true, advisorAlink:22, advisorBlink: 22, advisorClink: 22 }),
        knex('states').insert({name: 'Pennsylvania', state_tax_deduction: '$28,000', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Road Island', state_tax_deduction: '$1,000', load: '4',hasAdvisors:true, advisorAlink:23, advisorBlink: 23, advisorClink: 23 }),
        knex('states').insert({name: 'South Carolina', state_tax_deduction: 'Full state tax', load: '3.75',hasAdvisors:true, advisorAlink:25, advisorBlink: 25, advisorClink: 25}),
        knex('states').insert({name: 'South Dakota', state_tax_deduction: 'No state taxes',load:'5.5',hasAdvisors:true, advisorAlink:17, advisorBlink: 22, advisorClink: 20 }),
        knex('states').insert({name: 'Tennessee', state_tax_deduction: 'No deductions', load: 'none',hasAdvisors:false, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Texas', state_tax_deduction: 'No state taxes', load:'5',hasAdvisors:true, advisorAlink:17, advisorBlink: 22, advisorClink: 20}),
        knex('states').insert({name: 'Utah', state_tax_deduction: '$95 (tax credit)', load: 'none',hasAdvisors:false}),
        knex('states').insert({name: 'Vermont', state_tax_deduction: '$5,000', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'Virgina', state_tax_deduction: 'Full state tax', load: 'none',hasAdvisors:false, shouldDoDirect: true}),
        knex('states').insert({name: 'West Virgina', state_tax_deduction: 'Full state tax', load: '5.5',hasAdvisors:true , advisorAlink:28, advisorBlink: 28, advisorClink: 28}),
        knex('states').insert({name: 'Wisconsion', state_tax_deduction: '$3,100', load: '4.75',hasAdvisors:true , advisorAlink:29, advisorBlink: 29, advisorClink: 29}),
      ]);
    });
};
